#pragma once

#include <raylib.h>
#include "types.c"

#define CLOUD_WIDTH  60
#define CLOUD_HEIGHT 25
#define CLOUD_LOWER_Y_PERCENTAGE 0.35
#define CLOUD_UPPER_Y_PERCENTAGE 0.15
#define CLOUD_DT 0.1
#define CLOUD_BASKET_PERCENTAGE_X 0.7
#define CLOUD_BASKET_PERCENTAGE_Y 0.7

#define BALL_RADIUS 8

#define SLINGSHOT_WIDTH 160
#define SLINGSHOT_HEIGHT (SLINGSHOT_WIDTH * 1.14)
#define SLINGSHOT_STRING_THICKNESS 5
#define SLINGSHOT_STRING_SEPARATION_X 0.3
#define SLINGSHOT_STRING_SEPARATION_Y 0.02
#define SLINGSHOT_MAX_RADIUS 150
#define SLINGSHOT_CENTER (Vector2){.x = GetScreenWidth()/2.0, .y = GetScreenHeight()-SLINGSHOT_HEIGHT}

#define SCORE_FONTSIZE  20
#define SCORE_PADDING_Y 10

#define GRAVITY_ACCELERATION 300
#define BALL_MAXIMUM_INITIAL_SPEED 600

#define COLOR_BACKGROUND       (Color){ 24,   24,  37, 255 }
#define COLOR_SLINGSHOT        (Color){ 137, 180, 250, 255 }
#define COLOR_BALL             (Color){ 243, 139, 168, 255 }
#define COLOR_SLINGSHOT_STRING (Color){ 205, 214, 244, 255 }
#define COLOR_CLOUD            (Color){ 230, 255, 230, 255 }
#define COLOR_SCORE            (Color){ 230, 255, 230, 255 }

#define POINTS_FOR_LOWER 1
#define POINTS_FOR_UPPER 2

#define BALL_COOLDOWN 1
